# Generated by Django 4.2 on 2023-04-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_programme_carrying_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='qualifying_criteria',
            field=models.JSONField(default=dict),
        ),
    ]
