# Generated by Django 4.2 on 2023-04-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_alter_programme_qualifying_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='number_of_admitted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programme',
            name='number_of_enrolled',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programme',
            name='qualifying_points',
            field=models.IntegerField(default=0),
        ),
    ]
