# Generated by Django 4.2 on 2023-04-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0004_programme_number_of_admitted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='carrying_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programme',
            name='number_of_admitted',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programme',
            name='number_of_applicants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programme',
            name='number_of_enrolled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programme',
            name='qualifying_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
