# Generated by Django 4.2 on 2023-04-28 00:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0007_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='faculty',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
