# Generated by Django 4.2 on 2023-04-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='center_numbr',
            new_name='center_number',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='subjects',
        ),
        migrations.AddField(
            model_name='candidate',
            name='grades',
            field=models.JSONField(default=dict),
        ),
    ]
